Challenge 2 pull request
kaguna/Yummy-Recipes pull request #3
Opened 2017-10-23 04:06 UTC by kaguna

This PR operates  CRUD (Create, Read, Update and Delete) operations to the categories and the recipes.

It implements the Test Driven Development to the OOP and the data structures in use.

To test manually, install the virtual environment  and then use pip to get the necessary apps for testing then store them in the requirements.txt

In the pivot tracker, the stories revolve around towards achieving the CRUD opertaions to the users, category and users.

2017-11-01 06:51 UTC, Sylvance commented
Nice job. Coverage looks good and its builds well.

2017-11-01 09:14 UTC, jonathankamau requested changes
Please use pep8 to check for issues in your code. You have several files that do not have new lines at the end.

2017-11-02 05:47 UTC, jonathankamau requested changes
I still see that some of your files are missing a new line at the end of the file. Please correct this.

2017-11-02 05:47 UTC, jonathankamau requested changes
You have 263 issues to fix on code climate. Please check on this

2017-11-02 05:48 UTC, jonathankamau requested changes
Your travis build is failing and your test coverage has dropped. Please investigate this.

2017-11-03 06:10 UTC, jonathankamau commented on classes/users.py
> +        if re.match(regusername, nonspace_username):
From line 22 to 41 those are too many `if` statements :flushed: please see how you can refactor that.

2017-11-03 07:23 UTC, merged